// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3aZtVIO4PrTw3m44sOBh9YzF9VN8QJyc',
    appId: '1:645428051292:web:b520edc972326a40bd9599',
    messagingSenderId: '645428051292',
    projectId: 'daily-plus-adb31',
    authDomain: 'daily-plus-adb31.firebaseapp.com',
    storageBucket: 'daily-plus-adb31.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBclbfkxRbWrD-LUn4QrYVPYE2IQ0GnOHA',
    appId: '1:645428051292:android:ca73eb9fdd2cf000bd9599',
    messagingSenderId: '645428051292',
    projectId: 'daily-plus-adb31',
    storageBucket: 'daily-plus-adb31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjOi-9P27bIOS-aoXnhM29LR_xVSyiuMc',
    appId: '1:645428051292:ios:dd0544d298c5c38bbd9599',
    messagingSenderId: '645428051292',
    projectId: 'daily-plus-adb31',
    storageBucket: 'daily-plus-adb31.firebasestorage.app',
    iosBundleId: 'com.example.dailyPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjOi-9P27bIOS-aoXnhM29LR_xVSyiuMc',
    appId: '1:645428051292:ios:dd0544d298c5c38bbd9599',
    messagingSenderId: '645428051292',
    projectId: 'daily-plus-adb31',
    storageBucket: 'daily-plus-adb31.firebasestorage.app',
    iosBundleId: 'com.example.dailyPlus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3aZtVIO4PrTw3m44sOBh9YzF9VN8QJyc',
    appId: '1:645428051292:web:2a2aaccc6a044b01bd9599',
    messagingSenderId: '645428051292',
    projectId: 'daily-plus-adb31',
    authDomain: 'daily-plus-adb31.firebaseapp.com',
    storageBucket: 'daily-plus-adb31.firebasestorage.app',
  );
}
